// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmbfqcViEGTSuwlbN7KDCdfoKiBAtD8xg',
    appId: '1:577749510790:web:f8cc1e2cba97878d407f07',
    messagingSenderId: '577749510790',
    projectId: 'insta-d3feb',
    authDomain: 'insta-d3feb.firebaseapp.com',
    storageBucket: 'insta-d3feb.appspot.com',
    measurementId: 'G-L3C22WDEJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR2TYHmAPU3Pr4F5MVHjjHJ2F29OSTkgw',
    appId: '1:577749510790:android:9a5671e1a89d7d98407f07',
    messagingSenderId: '577749510790',
    projectId: 'insta-d3feb',
    storageBucket: 'insta-d3feb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK4dJlt9z0cQRTZNsWt6K2cErO7obKcpU',
    appId: '1:577749510790:ios:e8f626edd2e58067407f07',
    messagingSenderId: '577749510790',
    projectId: 'insta-d3feb',
    storageBucket: 'insta-d3feb.appspot.com',
    iosClientId: '577749510790-iieprsme3l3s296hcd73tilnuf00d1pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
